/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumextremep;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author Linda
 */
public class CreateBlogg extends javax.swing.JFrame {

    /**
     * Creates new form CreateBlogg
     */
    public CreateBlogg() {
        initComponents();
        setLocationRelativeTo(null);
        fyllBloggar(); 
        fyllAnvandare();
        fyllSubkategori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFTitle = new javax.swing.JTextField();
        CbUser = new javax.swing.JComboBox<>();
        spBlogFlow = new javax.swing.JScrollPane();
        TaCreateBlog = new javax.swing.JTextArea();
        cbBlog = new javax.swing.JComboBox<>();
        CbCategory = new javax.swing.JComboBox<>();
        LbCreateCategory = new javax.swing.JLabel();
        TfNewCategory = new javax.swing.JTextField();
        BtNewCategory = new javax.swing.JButton();
        BtAddFile = new javax.swing.JButton();
        BtCreateBlog = new javax.swing.JButton();
        lblRubrik = new java.awt.Label();
        lblBakgrundVit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TFTitle.setText("Titel");
        getContentPane().add(TFTitle);
        TFTitle.setBounds(240, 130, 220, 30);

        getContentPane().add(CbUser);
        CbUser.setBounds(780, 140, 130, 30);

        TaCreateBlog.setColumns(20);
        TaCreateBlog.setRows(5);
        spBlogFlow.setViewportView(TaCreateBlog);

        getContentPane().add(spBlogFlow);
        spBlogFlow.setBounds(240, 170, 510, 390);

        getContentPane().add(cbBlog);
        cbBlog.setBounds(780, 190, 130, 30);

        getContentPane().add(CbCategory);
        CbCategory.setBounds(780, 250, 130, 30);

        LbCreateCategory.setText("Skapa ny kategori");
        getContentPane().add(LbCreateCategory);
        LbCreateCategory.setBounds(780, 310, 110, 20);
        getContentPane().add(TfNewCategory);
        TfNewCategory.setBounds(780, 340, 130, 30);

        BtNewCategory.setText("Lägg till kategori");
        BtNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNewCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(BtNewCategory);
        BtNewCategory.setBounds(780, 390, 110, 20);

        BtAddFile.setText("Bifoga fil");
        getContentPane().add(BtAddFile);
        BtAddFile.setBounds(800, 430, 73, 23);

        BtCreateBlog.setText("Skapa blogginlägg");
        BtCreateBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCreateBlogActionPerformed(evt);
            }
        });
        getContentPane().add(BtCreateBlog);
        BtCreateBlog.setBounds(780, 510, 119, 40);

        lblRubrik.setAlignment(java.awt.Label.CENTER);
        lblRubrik.setBackground(new java.awt.Color(255, 255, 255));
        lblRubrik.setFont(new java.awt.Font("Impact", 0, 52)); // NOI18N
        lblRubrik.setText("Informatikblogg");
        getContentPane().add(lblRubrik);
        lblRubrik.setBounds(260, 0, 480, 120);

        lblBakgrundVit.setBackground(java.awt.Color.white);
        lblBakgrundVit.setForeground(new java.awt.Color(255, 255, 255));
        lblBakgrundVit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scrumextremep/Namnlös.jpg"))); // NOI18N
        lblBakgrundVit.setText("jLabel1");
        getContentPane().add(lblBakgrundVit);
        lblBakgrundVit.setBounds(0, -10, 1000, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNewCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtNewCategoryActionPerformed

    private void BtCreateBlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCreateBlogActionPerformed
     
        
        try {
        String blogText = TaCreateBlog.getText();
        String blogType = cbBlog.getSelectedItem().toString();
        String user = CbUser.getSelectedItem().toString(); 
        String sub = CbCategory.getSelectedItem().toString();
        String titel = TFTitle.getText();
        
        // skriva ComboBox för subKategorier, skriva kod för att lägga till kategori samt uppdatera och rensa textfield  
      
        String CbBlog = "SELECT B_ID FROM BLOGG WHERE BLOGGNAMN = '"+ blogType +"'";
        CbBlog = Databas.getDatabas().fetchSingle(CbBlog);
        String subC = "SELECT SK_ID FROM SUBKATEGORI WHERE SUBKATEGORI.NAMN = '" + sub + "'";
        subC = Databas.getDatabas().fetchSingle(subC);
        String userC = "SELECT A_ID FROM ANVANDARE WHERE ANVNAMN = '" + user + "'";
        userC = Databas.getDatabas().fetchSingle(userC);
        String BiID = Databas.getDatabas().getAutoIncrement("Blogginlagg" , "BI_ID");
        
        String sql = "INSERT INTO BLOGGINLAGG values ('" + BiID +  "', '" + titel + "' , '" + blogText + "','"+"fil"+"', "+ userC +", "+ subC +" ," + CbBlog + ")";
        Databas.getDatabas().insert(sql);
                
        JOptionPane.showMessageDialog(null, "Blogg inlägget har skapats");
        
      } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel: " + ex);
            }
      
    }//GEN-LAST:event_BtCreateBlogActionPerformed

    public void fyllBloggar()
    {
        try{
        String fyll = "SELECT BLOGGNAMN FROM BLOGG";
        ArrayList<HashMap<String, String>> bloggarna = Databas.getDatabas().fetchRows(fyll);
        for (int i = 0; i < bloggarna.size(); i++){
            cbBlog.addItem(bloggarna.get(i).get("BLOGGNAMN"));
                                                  }
           }
        catch(InfException e){
            System.out.println(e);
        }
    }
    
        public void fyllAnvandare()
    {
        try{
        String fyll = "SELECT FORNAMN, EFTERNAMN FROM ANVANDARE";
        ArrayList<HashMap<String, String>> bloggarna = Databas.getDatabas().fetchRows(fyll);
        for (int i = 0; i < bloggarna.size(); i++)
        {
            String namn = bloggarna.get(i).get("FORNAMN") + " " + bloggarna.get(i).get("EFTERNAMN");
            CbUser.addItem(namn);
        }
        }
        catch(InfException e){
            System.out.println(e);
        }
    }
    
    public void fyllSubkategori()
    {
        try{
            String bloggnamn = cbBlog.getSelectedItem().toString();
        String fyll = "SELECT NAMN FROM SUBKATEGORI WHERE B_ID = (SELECT B_ID FROM BLOGG WHERE BLOGGNAMN = '" + bloggnamn + "')";
        ArrayList<HashMap<String, String>> bloggarna = Databas.getDatabas().fetchRows(fyll);
        if(bloggarna != null){
        for (int i = 0; i < bloggarna.size(); i++)
        {
            CbCategory.addItem(bloggarna.get(i).get("NAMN"));
        }
        }
        }
        catch(InfException e){
            System.out.println(e);
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBlogg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddFile;
    private javax.swing.JButton BtCreateBlog;
    private javax.swing.JButton BtNewCategory;
    private javax.swing.JComboBox<String> CbCategory;
    private javax.swing.JComboBox<String> CbUser;
    private javax.swing.JLabel LbCreateCategory;
    private javax.swing.JTextField TFTitle;
    private javax.swing.JTextArea TaCreateBlog;
    private javax.swing.JTextField TfNewCategory;
    private javax.swing.JComboBox<String> cbBlog;
    private javax.swing.JLabel lblBakgrundVit;
    private java.awt.Label lblRubrik;
    private javax.swing.JScrollPane spBlogFlow;
    // End of variables declaration//GEN-END:variables
}
