/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumextremep;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfred
 */
public class InloggadSida extends javax.swing.JFrame {

    /**
     * Creates new form InloggadSida
     */
    public InloggadSida() {
        initComponents();
        fetchBlognames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBlog = new javax.swing.JTable();
        spCalender = new javax.swing.JScrollPane();
        taCalender = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblBakgrundVit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        lblRubrik.setAlignment(java.awt.Label.CENTER);
        lblRubrik.setBackground(new java.awt.Color(255, 255, 255));
        lblRubrik.setFont(new java.awt.Font("Impact", 0, 52)); // NOI18N
        lblRubrik.setText("Informatikblogg");
        getContentPane().add(lblRubrik);
        lblRubrik.setBounds(270, 10, 480, 120);

        tblBlog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titel", "Användare"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBlog);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(772, 212, 210, 360);

        taCalender.setColumns(20);
        taCalender.setRows(5);
        taCalender.setText("Här ska kalendern \nligga");
        spCalender.setViewportView(taCalender);

        getContentPane().add(spCalender);
        spCalender.setBounds(30, 210, 223, 150);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("efkesfkeak\n");
        jScrollPane2.setViewportView(jTextArea1);

        jTabbedPane1.addTab("tab1", jScrollPane2);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jTabbedPane1.addTab("tab2", jScrollPane3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(270, 190, 490, 440);

        lblBakgrundVit.setBackground(java.awt.Color.white);
        lblBakgrundVit.setForeground(new java.awt.Color(255, 255, 255));
        lblBakgrundVit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scrumextremep/Namnlös.jpg"))); // NOI18N
        lblBakgrundVit.setText("jLabel1");
        getContentPane().add(lblBakgrundVit);
        lblBakgrundVit.setBounds(0, 0, 1000, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchBlognames() {
        String sqlquery = "select BLOGGINLAGG.TITEL from BLOGGINLAGG";
        ArrayList<HashMap<String, String>> blognames = new ArrayList<>();
        try {
         blognames = Databas.getDatabas().fetchRows(sqlquery);
         
         for(int i = 0; i < blognames.size(); i++) {
             String names = blognames.get(i).get("TITEL");
             
             DefaultTableModel dmt = (DefaultTableModel)tblBlog.getModel();
             
             dmt.addRow(new Object[] {names});
                 }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblBakgrundVit;
    private java.awt.Label lblRubrik;
    private javax.swing.JScrollPane spCalender;
    private javax.swing.JTextArea taCalender;
    private javax.swing.JTable tblBlog;
    // End of variables declaration//GEN-END:variables
}
